appname = expense-tracker-api
httpport = 8080
runmode = dev
copyrequestbody = true

storage_driver = csv
csv_user_file = data/users.csv
csv_expense_file = data/expenses.csv

postgres_dsn =
postgres_auto_migrate = false
